name: beautymirror
description: "An app with various features like skin analysis, self care, and more."
publish_to: 'none' 
version: 1.0.0+10

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^12.0.1
  cupertino_icons: ^1.0.8
  firebase_storage: ^12.3.6
  cached_network_image:
  shimmer:
  image_picker:
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.5.0
  connectivity_plus: ^6.1.5
  firebase_auth: ^5.6.2
  firebase_core: 3.15.1
  flutter_native_splash: null
  flutter_rating_bar: ^4.0.1
  get: null
  get_storage: null
  google_sign_in: ^7.2.0
  http: null
  iconsax: null
  intl: null
  logger: null
  lottie: ^3.3.1
  url_launcher: ^6.3.1
  flutter_svg: ^2.0.17
  sign_in_with_apple: ^7.0.1
  flutter_facebook_auth: ^7.1.2
  # twitter_login: ^4.4.2
  flutter_timezone: ^4.0.0
  timezone: ^0.10.0
  timeline_tile: ^2.0.0
  fl_chart: ^1.1.1
  google_fonts: ^6.2.1
  flutter_markdown: ^0.7.6+1
  uuid: ^4.5.1
  flutter_launcher_icons: ^0.14.4
  table_calendar: ^3.1.3
  country_flags: ^3.0.0
  # openai_dart: ^0.4.5
  flutter_local_notifications: ^19.0.0
  mapdescriptor: ^1.0.8
  purchases_flutter: ^9.6.2 #^8.6.1
  # workmanager:
  #   git:
  #     url: https://github.com/fluttercommunity/flutter_workmanager.git
  #     path: workmanager
  #     ref: main

  dotted_border: ^3.0.1
  firebase_ai: ^2.1.0
  flutter_staggered_animations: ^1.1.1
  signature: ^6.3.0
  camera: ^0.11.1
  cloud_functions: ^5.6.1
  pinput: ^5.0.1
  visibility_detector: ^0.4.0+2
  audioplayers: ^6.5.0
  flutter_cache_manager: ^3.4.1
  flutter_chat_ui: ^2.9.0
  flutter_chat_core: ^2.8.0
  local_auth: ^2.3.0
  local_auth_darwin: ^1.6.1
  local_auth_android: ^1.0.54
  record: ^6.1.2
  path_provider: ^2.1.5
  flyer_chat_image_message: ^2.2.2
  audio_waveforms: ^1.3.0
  just_audio: ^0.10.5


  flutter_localizations:
    sdk: flutter
      
  currency_code_to_currency_symbol: ^0.0.4
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/sounds/
    - assets/logos/
    - assets/images/
    - assets/images/animations/
    - assets/images/content/
    - assets/images/reviews/
    - assets/icons/payment_methods/
    - assets/icons/login/
    - assets/icons/chat/
    - assets/icons/misc/
    - assets/icons/emojis/
    - assets/icons/profile/
    - assets/images/on_boarding_images/
    - assets/images/achievements/

flutter_native_splash:
  image: "assets/logos/app_icon.png"
  background_image: "assets/images/splash_background.png"
  web: false
  android_12:
    image: "assets/logos/app_icon_android.png"
    background_image: "assets/images/splash_background.png"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/logos/app_icon_android.png"
  image_path_ios: "assets/logos/app_icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21
  adaptive_icon_background: "#A385E9"
  adaptive_icon_foreground: "assets/logos/app_icon.png"
  background_color_ios: "#A385E9"


# android_notification_icons:
#   image_path: "assets/logos/app_icon_transparent_background.png"
#   icon_name: 'ic_notification' # optional
