// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtNfdtikHmUsKrNRFzP1RBXuie19jUTfw',
    appId: '1:587635367697:web:c61adfac7731beeb0ab6b0',
    messagingSenderId: '587635367697',
    projectId: 'beauty-planner-26cc0',
    authDomain: 'beauty-planner-26cc0.firebaseapp.com',
    storageBucket: 'beauty-planner-26cc0.firebasestorage.app',
    measurementId: 'G-KC24E368V1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKwzvOr0ic0_FtcyHdnC9dB8SpmfB2-Vs',
    appId: '1:587635367697:android:f190a327b9d05a810ab6b0',
    messagingSenderId: '587635367697',
    projectId: 'beauty-planner-26cc0',
    storageBucket: 'beauty-planner-26cc0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfi-dbMOUGHwL-DANWXA6yuW3cdpFYKQU',
    appId: '1:587635367697:ios:491c0c9ecf1fca2a0ab6b0',
    messagingSenderId: '587635367697',
    projectId: 'beauty-planner-26cc0',
    storageBucket: 'beauty-planner-26cc0.firebasestorage.app',
    androidClientId: '587635367697-fhl312t5smhn4n6lfpgs06ukp2qe61it.apps.googleusercontent.com',
    iosClientId: '587635367697-4oe6dkp95dgdj5sfuqf0cr9fuimuhlj2.apps.googleusercontent.com',
    iosBundleId: 'app.beautymirror',
  );

}