// import 'package:flutter_gen/gen_l10n/app_localizations.dart';
// import 'package:get/get.dart';

// class Tips {
//   static List<String> tips = [
//     AppLocalizations.of(Get.context!)!
//         .trimYourPetSNailsRegularlyToPreventInjuriesAndDiscomfort,
//     AppLocalizations.of(Get.context!)!
//         .keepYourPetSCoatCleanAndBrushedToReduceSheddingAndMatting,
//     AppLocalizations.of(Get.context!)!
//         .provideFreshWaterDailyToEnsureProperHydration,
//     AppLocalizations.of(Get.context!)!
//         .regularlyCheckYourPetSEarsForSignsOfInfection,
//     AppLocalizations.of(Get.context!)!
//         .maintainAHealthyDietBasedOnYourPetSAgeAndSize,
//     AppLocalizations.of(Get.context!)!
//         .cleanYourPetSBeddingOftenToReduceAllergens,
//     AppLocalizations.of(Get.context!)!
//         .ensureYourPetGetsEnoughExerciseToStayFitAndHealthy,
//     AppLocalizations.of(Get.context!)!
//         .scheduleRegularVetCheckupsToMonitorYourPetSHealth,
//     AppLocalizations.of(Get.context!)!
//         .keepYourPetSEnvironmentSafeAndFreeFromHazards,
//     AppLocalizations.of(Get.context!)!
//         .alwaysProvideShadeAndFreshWaterDuringHotWeather,
//     AppLocalizations.of(Get.context!)!
//         .brushYourPetSTeethRegularlyToPreventDentalIssues,
//     AppLocalizations.of(Get.context!)!.usePetSafeCleaningProductsAroundYourHome,
//     AppLocalizations.of(Get.context!)!
//         .watchForSignsOfFleasAndTicksEspeciallyInWarmerMonths,
//     AppLocalizations.of(Get.context!)!
//         .introduceNewFoodsSlowlyToAvoidDigestiveUpset,
//     AppLocalizations.of(Get.context!)!
//         .giveYourPetToysToKeepThemMentallyStimulated,
//     AppLocalizations.of(Get.context!)!
//         .avoidFeedingYourPetTableScrapsOrHumanSnacks,
//     AppLocalizations.of(Get.context!)!
//         .ensureYourPetHasAQuietSpaceToRestAndRelax,
//     AppLocalizations.of(Get.context!)!.keepToxicPlantsOutOfYourPetSReach,
//     AppLocalizations.of(Get.context!)!.useACollarWithIdTagsForAddedSafety,
//     AppLocalizations.of(Get.context!)!
//         .socializeYourPetWithOtherAnimalsGradually,
//     AppLocalizations.of(Get.context!)!.monitorYourPetSWeightToPreventObesity,
//     AppLocalizations.of(Get.context!)!.storePetFoodInACoolDryPlaceToKeepItFresh,
//     AppLocalizations.of(Get.context!)!
//         .provideScratchingPostsOrChewToysToProtectFurniture,
//     AppLocalizations.of(Get.context!)!.keepYourPetSVaccinationsUpToDate,
//     AppLocalizations.of(Get.context!)!.useAFleaCombToRegularlyCheckForParasites,
//     AppLocalizations.of(Get.context!)!
//         .giveYourPetPositiveReinforcementDuringTraining,
//     AppLocalizations.of(Get.context!)!
//         .watchForChangesInBehaviorTheyMaySignalHealthIssues,
//     AppLocalizations.of(Get.context!)!.avoidOverfeedingTreatsEvenHealthyOnes,
//     AppLocalizations.of(Get.context!)!
//         .keepYourHomeAtAComfortableTemperatureForYourPet,
//     AppLocalizations.of(Get.context!)!.cleanFoodAndWaterBowlsDaily,
//     AppLocalizations.of(Get.context!)!.neverLeaveYourPetInAParkedCar,
//     AppLocalizations.of(Get.context!)!
//         .protectYourPetSPawsFromHotPavementOrIcySurfaces,
//     AppLocalizations.of(Get.context!)!
//         .provideSoftBeddingForOlderPetsWithJointIssues,
//     AppLocalizations.of(Get.context!)!
//         .gentlyCleanAroundYourPetSEyesIfDischargeAppears,
//     AppLocalizations.of(Get.context!)!.keepAFirstAidKitReadyForPetEmergencies,
//     AppLocalizations.of(Get.context!)!
//         .introduceNewEnvironmentsSlowlyToReduceStress,
//     AppLocalizations.of(Get.context!)!.monitorBathroomHabitsForSignsOfIllness,
//     AppLocalizations.of(Get.context!)!.rotateToysToKeepYourPetInterested,
//     AppLocalizations.of(Get.context!)!
//         .ensureYourPetHasAccessToSunlightDuringTheDay,
//     AppLocalizations.of(Get.context!)!.useSlowFeedBowlsIfYourPetEatsTooQuickly,
//     AppLocalizations.of(Get.context!)!
//         .spendQualityTimeBondingWithYourPetEveryDay,
//     AppLocalizations.of(Get.context!)!
//         .provideVerticalSpacesForPetsToClimbAndExplore,
//     AppLocalizations.of(Get.context!)!.cleanLitterBoxesOrPottyAreasDaily,
//     AppLocalizations.of(Get.context!)!
//         .secureWindowsAndBalconiesToPreventAccidents,
//     AppLocalizations.of(Get.context!)!.rewardCalmBehaviorDuringGrooming,
//     AppLocalizations.of(Get.context!)!.usePositiveTonesWhenGivingCommands,
//     AppLocalizations.of(Get.context!)!.checkForTicksAfterWalksOrOutdoorPlay,
//     AppLocalizations.of(Get.context!)!
//         .keepSmallObjectsAwayFromPetsWhoMayChewThem,
//     AppLocalizations.of(Get.context!)!.useGentleShampoosDesignedForPets,
//     AppLocalizations.of(Get.context!)!
//         .letYourPetSniffAndExploreSafelyDuringWalks,
//     AppLocalizations.of(Get.context!)!.watchForLimpingOrSignsOfJointPain,
//     AppLocalizations.of(Get.context!)!.providePuzzleFeedersForMentalEnrichment,
//     AppLocalizations.of(Get.context!)!.offerGentleMassagesToRelaxYourPet,
//     AppLocalizations.of(Get.context!)!.avoidLoudNoisesThatCanScareYourPet,
//     AppLocalizations.of(Get.context!)!.neverUseHarshPunishmentItDamagesTrust,
//     AppLocalizations.of(Get.context!)!.keepElectricalCordsOutOfReach,
//     AppLocalizations.of(Get.context!)!.introduceGroomingToolsGradually,
//     AppLocalizations.of(Get.context!)!.trackVetVisitsAndVaccinationsInACalendar,
//     AppLocalizations.of(Get.context!)!.allowPetsToHideWhenTheyFeelStressed,
//     AppLocalizations.of(Get.context!)!.keepEmergencyVetContactsAccessible,
//     AppLocalizations.of(Get.context!)!.useProperCarriersForSafeTransport,
//     AppLocalizations.of(Get.context!)!.avoidBathingTooOftenItCanDryOutSkin,
//     AppLocalizations.of(Get.context!)!.offerHighPlacesOrHideoutsForPrivacy,
//     AppLocalizations.of(Get.context!)!.practiceBasicTrainingCommandsRegularly,
//     AppLocalizations.of(Get.context!)!
//         .stayCalmDuringStressfulSituationsToHelpYourPet,
//     AppLocalizations.of(Get.context!)!
//         .offerSafeSpacesDuringThunderstormsOrFireworks,
//     AppLocalizations.of(Get.context!)!
//         .watchForSignsOfAllergiesLikeItchingOrSneezing,
//     AppLocalizations.of(Get.context!)!.keepFoodPortionsMeasuredForHealthyWeight,
//     AppLocalizations.of(Get.context!)!
//         .avoidScentedLitterOrCleanersThatMayIrritatePets,
//     AppLocalizations.of(Get.context!)!.useReflectiveGearForNightWalks,
//     AppLocalizations.of(Get.context!)!.offerSoftToysForPetsThatLikeToCuddle,
//     AppLocalizations.of(Get.context!)!.replaceOldOrBrokenToysRegularly,
//     AppLocalizations.of(Get.context!)!.useGatesOrBarriersToManageSpace,
//     AppLocalizations.of(Get.context!)!.keepMedicationsAndChemicalsLockedAway,
//     AppLocalizations.of(Get.context!)!.checkForBurrsOrDebrisAfterOutdoorPlay,
//     AppLocalizations.of(Get.context!)!.superviseInteractionsWithChildren,
//     AppLocalizations.of(Get.context!)!.provideFreshAirThroughOpenSecureWindows,
//     AppLocalizations.of(Get.context!)!.bePatientWithNewOrAdoptedPets,
//     AppLocalizations.of(Get.context!)!.offerAMixOfPhysicalAndMentalActivities,
//     AppLocalizations.of(Get.context!)!.rewardYourPetAfterVetVisitsOrGrooming,
//     AppLocalizations.of(Get.context!)!.letPetsSniffNewPlacesAtTheirOwnPace,
//     AppLocalizations.of(Get.context!)!.useCalmingSpraysOrDiffusersIfNeeded,
//     AppLocalizations.of(Get.context!)!.setARoutineForFeedingAndPlaytime,
//     AppLocalizations.of(Get.context!)!
//         .donTIgnoreBadBreathItMaySignalDentalIssues,
//     AppLocalizations.of(Get.context!)!.watchForExcessiveScratchingOrLicking,
//     AppLocalizations.of(Get.context!)!.keepPetLicensesAndMicrochipInfoCurrent,
//     AppLocalizations.of(Get.context!)!
//         .allowPetsToObserveFromASafeDistanceWhenUnsure,
//     AppLocalizations.of(Get.context!)!.offerFrozenTreatsInSummerToCoolDown,
//     AppLocalizations.of(Get.context!)!
//         .protectYourPetFromHouseholdHolidayHazards,
//     AppLocalizations.of(Get.context!)!.limitExposureToLoudMusicOrStrongScents,
//     AppLocalizations.of(Get.context!)!.introduceGroomingEarlyToBuildTolerance,
//     AppLocalizations.of(Get.context!)!.checkYourPetSCoatForDrynessOrFlakes,
//     AppLocalizations.of(Get.context!)!
//         .watchWaterIntakeItMayRevealHealthProblems,
//     AppLocalizations.of(Get.context!)!
//         .offerASoftToyOrBlanketForComfortWhenAlone,
//     AppLocalizations.of(Get.context!)!
//         .useHarnessesInsteadOfCollarsForBetterControl,
//     AppLocalizations.of(Get.context!)!.stayAlertForSignsOfBoredomOrAnxiety,
//     AppLocalizations.of(Get.context!)!
//         .setRealisticTrainingGoalsAndCelebrateProgress,
//     AppLocalizations.of(Get.context!)!.useTreatsAndPraiseToTeachNewSkills,
//     AppLocalizations.of(Get.context!)!
//         .keepMealtimesConsistentToSupportDigestion,
//     AppLocalizations.of(Get.context!)!.avoidSuddenChangesToDietOrRoutine,
//     AppLocalizations.of(Get.context!)!
//         .checkYourPetSSkinForLumpsOrBumpsRegularly,
//     AppLocalizations.of(Get.context!)!
//         .keepYourPetCalmDuringTravelWithFamiliarItems,
//     AppLocalizations.of(Get.context!)!
//         .provideCompanionshipPetsNeedSocialInteraction,
//     AppLocalizations.of(Get.context!)!.avoidStrongPerfumesAroundYourPet,
//     AppLocalizations.of(Get.context!)!.washYourHandsAfterHandlingPetWaste,
//     AppLocalizations.of(Get.context!)!.trainYourPetUsingShortConsistentSessions,
//     AppLocalizations.of(Get.context!)!.storePetSuppliesInAnOrganizedDryPlace,
//     AppLocalizations.of(Get.context!)!.limitAccessToStairsForOlderPets,
//     AppLocalizations.of(Get.context!)!
//         .watchForSignsOfOverheatingLikeExcessivePanting,
//     AppLocalizations.of(Get.context!)!.createASafeRoutineForNailTrimming,
//     AppLocalizations.of(Get.context!)!
//         .useTreatsToAssociateGroomingWithPositiveExperiences,
//     AppLocalizations.of(Get.context!)!.beConsistentWithRulesAndBoundaries,
//     AppLocalizations.of(Get.context!)!
//         .letYourPetExploreDifferentTexturesAndSurfaces,
//     AppLocalizations.of(Get.context!)!.offerSafeChewsToSupportDentalHealth,
//     AppLocalizations.of(Get.context!)!.observeHowYourPetReactsToNewPeople,
//     AppLocalizations.of(Get.context!)!.letYourPetRetreatIfTheyFeelOverwhelmed,
//     AppLocalizations.of(Get.context!)!.offerIndoorEnrichmentOnRainyOrColdDays,
//     AppLocalizations.of(Get.context!)!.removeHairBuildupFromBrushesAfterEachUse,
//     AppLocalizations.of(Get.context!)!
//         .keepAPetTowelForDryingAfterBathsOrWetWalks,
//     AppLocalizations.of(Get.context!)!.teachBasicCommandsLikeSitAndStayEarly,
//     AppLocalizations.of(Get.context!)!.useQuietPraiseIfYourPetIsSoundSensitive,
//     AppLocalizations.of(Get.context!)!.avoidOverexercisingYoungOrSeniorPets,
//     AppLocalizations.of(Get.context!)!.keepInteractivePlayGentleAndFun,
//     AppLocalizations.of(Get.context!)!
//         .reintroduceTrainingCuesIfTheyAreForgotten,
//     AppLocalizations.of(Get.context!)!.watchYourPetSGaitForStiffnessOrPain,
//     AppLocalizations.of(Get.context!)!.avoidPhysicalPunishmentItCreatesFear,
//     AppLocalizations.of(Get.context!)!
//         .learnYourPetSBodyLanguageForBetterCommunication,
//     AppLocalizations.of(Get.context!)!.allowTimeForYourPetToAdjustAfterAMove,
//     AppLocalizations.of(Get.context!)!.useHandsFreeLeashesForSaferWalks,
//     AppLocalizations.of(Get.context!)!.introduceLeashesAndHarnessesGradually,
//     AppLocalizations.of(Get.context!)!.praiseCalmBehaviorDuringVetVisits,
//     AppLocalizations.of(Get.context!)!.avoidGivingBonesThatSplinterEasily,
//     AppLocalizations.of(Get.context!)!.giveTimeForYourPetToSettleAfterMeals,
//     AppLocalizations.of(Get.context!)!.superviseOutdoorPlayInUnfamiliarAreas,
//     AppLocalizations.of(Get.context!)!.offerBreaksDuringLongPlaySessions,
//     AppLocalizations.of(Get.context!)!
//         .letYourPetChooseTheirFavoriteSleepingSpot,
//     AppLocalizations.of(Get.context!)!.checkCollarsForProperFitRegularly,
//     AppLocalizations.of(Get.context!)!.watchForSignsOfSeparationAnxiety,
//     AppLocalizations.of(Get.context!)!.usePetSafeWipesForQuickCleanups,
//     AppLocalizations.of(Get.context!)!
//         .beMindfulOfWeatherWhenPlanningOutdoorTime,
//     AppLocalizations.of(Get.context!)!.teachCalmGreetingsWithGuests,
//     AppLocalizations.of(Get.context!)!.provideQuietTimeAfterIntensePlay,
//     AppLocalizations.of(Get.context!)!.recognizeWhenYourPetWantsSpace,
//     AppLocalizations.of(Get.context!)!.avoidPlayingRoughWithSmallPets,
//     AppLocalizations.of(Get.context!)!
//         .makeVetTripsLessStressfulWithTreatsAndPraise,
//     AppLocalizations.of(Get.context!)!.setUpAComfySpaceForRecoveryAfterIllness,
//     AppLocalizations.of(Get.context!)!.storePetTreatsOutOfReach,
//     AppLocalizations.of(Get.context!)!.watchOlderPetsForSignsOfArthritis,
//     AppLocalizations.of(Get.context!)!.useBabyGatesToCreatePetSafeZones,
//     AppLocalizations.of(Get.context!)!.checkToysForWearAndTearRegularly,
//     AppLocalizations.of(Get.context!)!.praiseGoodBehaviorConsistently,
//     AppLocalizations.of(Get.context!)!.useInteractiveToysToBeatBoredom,
//     AppLocalizations.of(Get.context!)!.keepPetGroomingSessionsShortAndCalm,
//     AppLocalizations.of(Get.context!)!.offerFrozenVeggiesAsLowCalorieTreats,
//     AppLocalizations.of(Get.context!)!.protectYourPetFromSharpGardenTools,
//     AppLocalizations.of(Get.context!)!.useSoftBrushesForSensitiveSkin,
//     AppLocalizations.of(Get.context!)!
//         .letYourPetSniffDuringWalksItSMentallyEnriching,
//     AppLocalizations.of(Get.context!)!.monitorStoolForSignsOfParasitesOrIllness,
//     AppLocalizations.of(Get.context!)!.washSoftToysToRemoveDirtAndBacteria,
//     AppLocalizations.of(Get.context!)!.keepYourPetInsideDuringExtremeWeather,
//     AppLocalizations.of(Get.context!)!.addVarietyToYourPetSPlayRoutine,
//     AppLocalizations.of(Get.context!)!.trackChangesInYourPetSAppetite,
//     AppLocalizations.of(Get.context!)!
//         .avoidOverstimulatingYourPetWithConstantNoise,
//     AppLocalizations.of(Get.context!)!.gentlyHandlePawsToMakeGroomingEasier,
//     AppLocalizations.of(Get.context!)!
//         .provideChewAlternativesToSaveYourFurniture,
//     AppLocalizations.of(Get.context!)!.useSoothingMusicToReduceStressAtHome,
//     AppLocalizations.of(Get.context!)!.offerComfortItemsWhenYourPetIsAlone,
//     AppLocalizations.of(Get.context!)!.useAConsistentToneWhenGivingCommands,
//     AppLocalizations.of(Get.context!)!.avoidFeedingSpoiledOrExpiredPetFood,
//     AppLocalizations.of(Get.context!)!.playHideAndSeekToEngageYourPetSMind,
//     AppLocalizations.of(Get.context!)!
//         .trainDuringQuietTimesToReduceDistractions,
//     AppLocalizations.of(Get.context!)!.giveGentlePraiseForSmallAccomplishments,
//     AppLocalizations.of(Get.context!)!.ensureYourPetHasVisualAndPhysicalPrivacy,
//     AppLocalizations.of(Get.context!)!.replaceWaterOftenEspeciallyInWarmWeather,
//     AppLocalizations.of(Get.context!)!.offerHighProteinTreatsAfterActivePlay,
//     AppLocalizations.of(Get.context!)!
//         .donTSkipVetAppointmentsEvenIfYourPetLooksFine,
//     AppLocalizations.of(Get.context!)!.monitorSeasonalAllergiesAndReactions,
//     AppLocalizations.of(Get.context!)!.keepAnEmergencyTravelBagReadyForYourPet,
//     AppLocalizations.of(Get.context!)!
//         .createACalmEnvironmentAfterSurgeryOrIllness,
//     AppLocalizations.of(Get.context!)!.useSecureEnclosuresForPetsInCars,
//     AppLocalizations.of(Get.context!)!.bePatientWithRescuesTheyNeedTimeToTrust,
//     AppLocalizations.of(Get.context!)!
//         .setRealisticExpectationsForTrainingProgress,
//     AppLocalizations.of(Get.context!)!.observeHowYourPetReactsToCertainFoods,
//     AppLocalizations.of(Get.context!)!.addSoftMatsOnSlipperyFloorsForTraction,
//     AppLocalizations.of(Get.context!)!
//         .trainGentlyUsingFoodToysOrAffectionAsRewards,
//     AppLocalizations.of(Get.context!)!
//         .offerPlentyOfPraiseForUsingTheLitterBoxOrOutdoors,
//     AppLocalizations.of(Get.context!)!.cleanUpAccidentsCalmlyAndThoroughly,
//     AppLocalizations.of(Get.context!)!.useWashablePetMatsToSimplifyCleanup,
//     AppLocalizations.of(Get.context!)!
//         .allowYourPetToSniffNewPeopleOrAnimalsFirst,
//     AppLocalizations.of(Get.context!)!.provideAgeAppropriateStimulation,
//     AppLocalizations.of(Get.context!)!.offerWarmBeddingInColdWeather,
//     AppLocalizations.of(Get.context!)!
//         .avoidOverBathingOnceAMonthIsUsuallyEnough,
//     AppLocalizations.of(Get.context!)!.learnYourPetSLikesAndDislikes,
//     AppLocalizations.of(Get.context!)!
//         .monitorForSignsOfFearLikeHidingOrTrembling,
//     AppLocalizations.of(Get.context!)!.useVetApprovedFleaAndTickPreventatives,
//     AppLocalizations.of(Get.context!)!
//         .checkFoodLabelsForUnnecessaryFillersOrSugars,
//     AppLocalizations.of(Get.context!)!.neverForceInteractionWithShyPets,
//     AppLocalizations.of(Get.context!)!.teachCalmLeashBehaviorFromAYoungAge,
//     AppLocalizations.of(Get.context!)!.useInteractiveFeedersToSlowFastEaters,
//     AppLocalizations.of(Get.context!)!.keepPlaySessionsBalancedWithRest,
//     AppLocalizations.of(Get.context!)!
//         .useSoftLightingToKeepYourPetRelaxedAtNight,
//     AppLocalizations.of(Get.context!)!.introduceNewFoodGraduallyOver710Days,
//     AppLocalizations.of(Get.context!)!
//         .provideRampsForOlderPetsWithMobilityIssues,
//     AppLocalizations.of(Get.context!)!
//         .watchForExcessiveMeowingOrBarkingItMaySignalStress,
//     AppLocalizations.of(Get.context!)!
//         .keepYourPetSNailsShortToPreventJointStrain,
//     AppLocalizations.of(Get.context!)!
//         .avoidRoughFlooringForPetsWithSensitivePaws,
//     AppLocalizations.of(Get.context!)!
//         .giveSpaceForYourPetToEatWithoutInterruption,
//     AppLocalizations.of(Get.context!)!.letYourPetExploreNewToysAtTheirOwnPace,
//     AppLocalizations.of(Get.context!)!
//         .offerVarietyInPlayChaseTugFetchHideAndSeek,
//     AppLocalizations.of(Get.context!)!.keepIndoorPlantsOutOfReachSomeAreToxic,
//     AppLocalizations.of(Get.context!)!.useWashableCoversOnFurnitureYourPetUses,
//     AppLocalizations.of(Get.context!)!
//         .provideRegularMentalChallengesToReduceAnxiety,
//     AppLocalizations.of(Get.context!)!
//         .letYourPetSniffOtherPetsOnlyUnderSupervision,
//     AppLocalizations.of(Get.context!)!
//         .avoidPhysicalForceDuringAnyTypeOfTraining,
//     AppLocalizations.of(Get.context!)!.limitChangesToYourPetSDailyRoutine,
//     AppLocalizations.of(Get.context!)!.useCalmingSpraysForTravelOrVetVisits,
//     AppLocalizations.of(Get.context!)!.watchYourPetSBreathingRateDuringRest,
//     AppLocalizations.of(Get.context!)!.provideShadedAreasForOutdoorPets,
//     AppLocalizations.of(Get.context!)!.neverSkipFleaAndWormPrevention,
//     AppLocalizations.of(Get.context!)!.createAQuietZoneInYourHomeJustForYourPet,
//     AppLocalizations.of(Get.context!)!.donTShoutItCanIncreaseFearOrAnxiety,
//     AppLocalizations.of(Get.context!)!
//         .observeHowYourPetInteractsWithDifferentTextures,
//     AppLocalizations.of(Get.context!)!.avoidPlacingLitterBoxesOrPeePadsNearFood,
//     AppLocalizations.of(Get.context!)!.keepTrashBinsPetProof,
//     AppLocalizations.of(Get.context!)!.offerACoolingMatDuringHotWeather,
//     AppLocalizations.of(Get.context!)!
//         .encourageGentlePlayBetweenPetsAndChildren,
//     AppLocalizations.of(Get.context!)!.donTForceEyeContactWithANervousPet,
//     AppLocalizations.of(Get.context!)!.provideExtraCareAndComfortDuringRecovery,
//     AppLocalizations.of(Get.context!)!
//         .trackYourPetSHabitsToSpotEarlyHealthIssues,
//     AppLocalizations.of(Get.context!)!.usePetSafeDeodorizersForLitterBoxes,
//     AppLocalizations.of(Get.context!)!.letYourPetRestAfterVaccinations,
//     AppLocalizations.of(Get.context!)!
//         .adjustFoodPortionsWithChangesInActivityLevels,
//     AppLocalizations.of(Get.context!)!
//         .avoidChasingYourPetDuringPlayItMayScareThem,
//     AppLocalizations.of(Get.context!)!.providePlentyOfQuietUndisturbedSleepTime,
//     AppLocalizations.of(Get.context!)!.donTScoldForAccidentsRedirectGently,
//     AppLocalizations.of(Get.context!)!.useClearConsistentCuesForTraining,
//     AppLocalizations.of(Get.context!)!.offerSafeUnscentedChewToys,
//     AppLocalizations.of(Get.context!)!.checkForCrackedPawPadsDuringWinter,
//     AppLocalizations.of(Get.context!)!.ensureYourPetAlwaysHasAccessToCleanWater,
//     AppLocalizations.of(Get.context!)!.encourageGentleTouchDuringHandling,
//     AppLocalizations.of(Get.context!)!.letPetsGetUsedToNewCarriersBeforeTravel,
//     AppLocalizations.of(Get.context!)!.useSlowFeedersToPreventBloating,
//     AppLocalizations.of(Get.context!)!.takeBreaksOnLongTripsWithYourPet,
//     AppLocalizations.of(Get.context!)!
//         .bePatientWithNewlyAdoptedPetsTheyNeedTime,
//     AppLocalizations.of(Get.context!)!.keepDangerousCordsAndChargersOutOfReach,
//     AppLocalizations.of(Get.context!)!.offerSimpleCommandsBeforeComplexTricks,
//     AppLocalizations.of(Get.context!)!
//         .donTSwitchDietsAbruptlyItMayUpsetDigestion,
//     AppLocalizations.of(Get.context!)!.useWashableRugsToSimplifyCleanup,
//     AppLocalizations.of(Get.context!)!
//         .watchForExcessiveLickingItMaySignalAnxiety,
//     AppLocalizations.of(Get.context!)!.protectPawsFromSnowSaltOrHotSurfaces,
//     AppLocalizations.of(Get.context!)!
//         .letYourPetAdjustGraduallyToNewFamilyMembers,
//     AppLocalizations.of(Get.context!)!.provideADesignatedPlayZoneAtHome,
//     AppLocalizations.of(Get.context!)!.avoidRoughToysThatCanInjureGums,
//     AppLocalizations.of(Get.context!)!.checkForFurMatsInHardToReachAreas,
//     AppLocalizations.of(Get.context!)!
//         .offerTreatsOnlyForGoodBehaviorNotToStopWhining,
//     AppLocalizations.of(Get.context!)!.recognizeBreedSpecificBehaviorsAndNeeds,
//     AppLocalizations.of(Get.context!)!
//         .keepYourPetSScheduleConsistentDuringHolidays,
//     AppLocalizations.of(Get.context!)!.provideCozyBlanketsForColderMonths,
//     AppLocalizations.of(Get.context!)!
//         .avoidUsingLasersWithoutGivingARewardAtTheEnd,
//     AppLocalizations.of(Get.context!)!
//         .giveAttentionDailyEvenShortSessionsMatter,
//     AppLocalizations.of(Get.context!)!.neverSkipHydrationDuringWalksOrPlay,
//     AppLocalizations.of(Get.context!)!.introduceBrushingEarlyAndGently,
//     AppLocalizations.of(Get.context!)!.useSoftBeddingToEaseJointPressure,
//     AppLocalizations.of(Get.context!)!.respectYourPetSBoundariesDuringPlay,
//     AppLocalizations.of(Get.context!)!.avoidFeedingPetsRightBeforeTravel,
//     AppLocalizations.of(Get.context!)!.keepWaterBowlsCleanToPreventBacteria,
//     AppLocalizations.of(Get.context!)!
//         .letYourPetWalkOnGrassRatherThanHotPavement,
//     AppLocalizations.of(Get.context!)!
//         .observeDailyEnergyLevelsForSignsOfIllness,
//     AppLocalizations.of(Get.context!)!.useAPetCameraToMonitorBehaviorWhenAway,
//     AppLocalizations.of(Get.context!)!.giveMultipleRestBreaksDuringTraining,
//     AppLocalizations.of(Get.context!)!.useMildPetWipesBetweenBaths,
//     AppLocalizations.of(Get.context!)!.offerPraiseEvenForSmallProgress,
//     AppLocalizations.of(Get.context!)!.provideASafeHidingPlaceForShyPets,
//     AppLocalizations.of(Get.context!)!.encourageGentleGreetingsWithStrangers,
//     AppLocalizations.of(Get.context!)!.usePositiveCuesDuringGrooming,
//     AppLocalizations.of(Get.context!)!.offerEdibleChewsToSupportOralHealth,
//     AppLocalizations.of(Get.context!)!.keepSharpGroomingToolsSafelyStored,
//     AppLocalizations.of(Get.context!)!.createAConsistentBedtimeRoutine,
//     AppLocalizations.of(Get.context!)!.stayCalmWhenCleaningUpPetMesses,
//     AppLocalizations.of(Get.context!)!.keepPlaytimeSessionsShortForSeniorPets,
//     AppLocalizations.of(Get.context!)!.introduceNewPetsSlowlyAndWithSupervision,
//     AppLocalizations.of(Get.context!)!.offerACalmDarkRoomDuringFireworks,
//     AppLocalizations.of(Get.context!)!.provideDailyEnrichmentEvenForIndoorPets,
//     AppLocalizations.of(Get.context!)!.avoidSkippingMealsItDisruptsDigestion,
//     AppLocalizations.of(Get.context!)!.useNonSlipBowlsForEagerEaters,
//     AppLocalizations.of(Get.context!)!.letYourPetRestAfterVigorousPlay,
//     AppLocalizations.of(Get.context!)!.avoidWearingStrongScentsAroundPets,
//     AppLocalizations.of(Get.context!)!.usePuzzleMatsToChallengeTheirMind,
//     AppLocalizations.of(Get.context!)!.rewardCalmnessDuringStorms,
//     AppLocalizations.of(Get.context!)!.neverTeaseYourPetItCausesStress,
//     AppLocalizations.of(Get.context!)!.offerFrozenBrothCubesAsAHydratingTreat,
//     AppLocalizations.of(Get.context!)!.rewardCrateTimeWithToysAndTreats,
//     AppLocalizations.of(Get.context!)!.offerFoodDispensingToysToSlowEating,
//     AppLocalizations.of(Get.context!)!
//         .useNaturalLightToRegulateYourPetSSleepCycle,
//     AppLocalizations.of(Get.context!)!.watchYourPetSGaitOnStairsForStiffness,
//     AppLocalizations.of(Get.context!)!.avoidLeashPullingItCanInjureTheNeck,
//     AppLocalizations.of(Get.context!)!.offerVarietyInTreatsToPreventBoredom,
//     AppLocalizations.of(Get.context!)!
//         .teachCalmExitsAndEntrancesToPreventAnxiety,
//     AppLocalizations.of(Get.context!)!.superviseOpenWindowsEvenWithScreens,
//     AppLocalizations.of(Get.context!)!
//         .celebrateYourPetSMilestonesWithLoveAndCare,
//   ];
// }
